{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d993ae0b",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 1\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d8a7f8f9",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "38f0a5e6",
   "metadata": {},
   "source": [
    "**User**\n",
    "\n",
    "I'm getting an 'IndexError' in my list processing loop. Can you demonstrate how to use a debugger to pinpoint where it's going wrong?\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
