{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a546092b",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 3\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "91581fec",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "755d4242",
   "metadata": {},
   "source": [
    "**User**\n",
    "\n",
    "Not Running in Fish Shell\n",
    "\n",
    "<!-- If you have any issue with The Fuck, sorry about that, but we will do what we\r\n",
    "can to fix that. Actually, maybe we already have, so first thing to do is to\r\n",
    "update The Fuck and see if the bug is still there. -->\r\n",
    "\r\n",
    "<!-- If it is (sorry again), check if the problem has not already been reported and\r\n",
    "if not, just open an issue on [GitHub](https://github.com/nvbn/thefuck) with\r\n",
    "the following basic information: -->\r\n",
    "\r\n",
    "The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):\r\n",
    "\r\n",
    "**The Fuck 3.26 using Python 3.6.5**\r\n",
    "\r\n",
    "Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):\r\n",
    "\r\n",
    "**Fish v2.7.1 (works fine in Bash)**\r\n",
    "\r\n",
    "Your system (Debian 7, ArchLinux, Windows, etc.):\r\n",
    "\r\n",
    "**macOS 10.13.5 Beta (17F45c)**\r\n",
    "\r\n",
    "How to reproduce the bug:\r\n",
    "\r\n",
    "**Run 'fuck' command after entering any incorrect command in Fish shell.**\r\n",
    "\r\n",
    "The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):\r\n",
    "\r\n",
    "```\r\n",
    "DEBUG: Run with settings: {'alter_history': True,\r\n",
    " 'debug': True,\r\n",
    " 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},\r\n",
    " 'exclude_rules': [],\r\n",
    " 'history_limit': None,\r\n",
    " 'instant_mode': False,\r\n",
    " 'no_colors': False,\r\n",
    " 'priority': {},\r\n",
    " 'repeat': False,\r\n",
    " 'require_confirmation': True,\r\n",
    " 'rules': [<const: All rules enabled>],\r\n",
    " 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],\r\n",
    " 'user_dir': PosixPath('/Users/user/.config/thefuck'),\r\n",
    " 'wait_command': 3,\r\n",
    " 'wait_slow_command': 15}\r\n",
    "DEBUG: Total took: 0:00:00.296931\r\n",
    "Traceback (most recent call last):\r\n",
    "  File \"/usr/local/bin/thefuck\", line 12, in <module>\r\n",
    "    sys.exit(main())\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/entrypoints/main.py\", line 25, in main\r\n",
    "    fix_command(known_args)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/entrypoints/fix_command.py\", line 36, in fix_command\r\n",
    "    command = types.Command.from_raw_script(raw_command)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/types.py\", line 81, in from_raw_script\r\n",
    "    expanded = shell.from_shell(script)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/shells/generic.py\", line 30, in from_shell\r\n",
    "    return self._expand_aliases(command_script)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/shells/fish.py\", line 65, in _expand_aliases\r\n",
    "    aliases = self.get_aliases()\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/shells/fish.py\", line 60, in get_aliases\r\n",
    "    raw_aliases = _get_aliases(overridden)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/utils.py\", line 33, in wrapper\r\n",
    "    memo[key] = fn(*args, **kwargs)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/utils.py\", line 267, in wrapper\r\n",
    "    return _cache.get_value(fn, depends_on, args, kwargs)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/utils.py\", line 243, in get_value\r\n",
    "    value = fn(*args, **kwargs)\r\n",
    "  File \"/usr/local/Cellar/thefuck/3.26/libexec/lib/python3.6/site-packages/thefuck/shells/fish.py\", line 25, in _get_aliases\r\n",
    "    name, value = alias.replace('alias ', '', 1).split(' ', 1)\r\n",
    "ValueError: not enough values to unpack (expected 2, got 1)\r\n",
    "```\r\n",
    "\r\n",
    "If the bug only appears with a specific application, the output of that application and its version:\r\n",
    "\r\n",
    "N/A\r\n",
    "\r\n",
    "Anything else you think is relevant:\r\n",
    "\r\n",
    "N/A\r\n",
    "\r\n",
    "![screenshot_20180426_17 50 13_tz8le7](https://user-images.githubusercontent.com/742476/39339042-64896c24-497b-11e8-992b-ee41abf71a0c.png)\r\n",
    "\r\n",
    "\r\n",
    "<!-- It's only with enough information that we can do something to fix the problem. -->\r\n",
    "\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
